# Generated by Django 3.0.3 on 2020-03-12 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_handle', models.CharField(max_length=15)),
                ('user_name', models.CharField(default='PH', max_length=25)),
                ('password', models.CharField(default='', max_length=128)),
                ('acc_create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('followed_users', models.CharField(default=',', max_length=1000)),
                ('liked_tweets', models.CharField(default=',', max_length=1000)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('user_acc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_post', 'can_delete_self_posts')],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(default='', max_length=280)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('likes', models.IntegerField(default=0)),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tweets.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.CharField(max_length=280)),
                ('reply_poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tweets.Profile')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.Tweet')),
            ],
        ),
    ]
