# Generated by Django 3.0.3 on 2020-03-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200312_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed_users',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_tweets',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
