# Generated by Django 3.0.3 on 2020-03-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20200312_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_path',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
