# Generated by Django 3.0.3 on 2020-03-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_profile_profile_picture_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_path',
        ),
    ]
