# Generated by Django 3.0.3 on 2020-03-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_remove_profile_profile_picture_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
