# Generated by Django 3.0.3 on 2020-03-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20200313_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
